os: linux
dist: focal

services:
- docker

jobs:
  include:
  - stage: build docker image
    script:
    - docker build -t $DOCKER_USERNAME/spinkub-demo-v2 .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/spinkub-demo-v2:latest
